apiVersion: v2
name: elder
description: Elder - Asset Discovery and Management Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Penguin Tech Inc
    email: support@penguintech.io
    url: https://www.penguintech.io
keywords:
  - asset-management
  - discovery
  - security
  - monitoring
home: https://github.com/penguintechinc/elder
sources:
  - https://github.com/penguintechinc/elder
