apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elder.fullname" . }}-secrets
  labels:
    {{- include "elder.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "elder.databaseUrl" . | quote }}
  redis-url: {{ include "elder.redisUrl" . | quote }}
  secret-key: {{ required "config.secretKey is required" .Values.config.secretKey | quote }}
  license-key: {{ .Values.config.license.key | default "" | quote }}
