{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elder.fullname" . }}-web
  labels:
    {{- include "elder.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
  - port: {{ .Values.web.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.web.service.type "NodePort") .Values.web.service.nodePort }}
    nodePort: {{ .Values.web.service.nodePort }}
    {{- end }}
  selector:
    {{- include "elder.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}
