apiVersion: v1
kind: Namespace
metadata:
  name: elder
  labels:
    app.kubernetes.io/name: elder
    app.kubernetes.io/instance: elder
    app.kubernetes.io/managed-by: github-actions
    environment: production
